version: '3.8'

services:
  oracle-xe:
    image: gvenzl/oracle-xe:latest
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=
    volumes:
      - /opt/sqldeveloper/oracle-docker:/opt/sqldeveloper/oracle-docker
    networks:
      - oracle_network
    restart: unless-stopped

networks:
  oracle_network:
    driver: bridge
